
EXCEPTION_DETAILS = {

    "0001": "INVALID_REQUEST_DATA",
    "0002": "ERROR_DECODING_JSON_DATA",
    "0003": "ERROR_LOADING_PDF_FILE_DATA",
    "0004": "INVALID_DATA_FEEDER_FILE_EXTENSION",
    "0005": "FAILED_TO_LOAD_JSON_FEEDER_DATA",
    "0006": "INVALID_TEXT_SPLITTER_REQUEST",
    "0007": "FAILED_TO_EMBEDD_DATA",
    "0008": "INVALID_EMBEDDING_REQUEST",
    "0009": "FAILED_TO_CREATE_VECTOR_STORE",
    "0010": "FAILED_TO_GENERATE_RESPONSE"
}
